### ISSUE TITLE
i cannot make it work 

### ISSUE THREAD

**Issue by Guscal** [keshon/kitsu-to-discord-task-notification#1]
i dont know what im doing wrong i filled the conf file and the exe doestno seam to open it just opens the cmd and dies, i added the webhook and nothing, do i have to add it to a bot? m, i tried downloading the  the release filled that conf file and nothing :c

**Comment by Guscal** [comment]
panic: failed to connect database is the messsage in cmd c:/kitsu-to-discord-task-notification-master/src/main.go:364 +0xa18

**Comment by keshon** [comment]
Hi! Recent Kitsu version supports Discord notification out of the box so you don't need to use this implementation.
If you still want to try to run it - let me check it tomorrow and and apply fix if nessesary

**Comment by Guscal** [comment]
Thank you so much!, I could not make that one work either Haha :/, i followed the documentation and nothing.

**Comment by keshon** [comment]
I tested the repo and it's working.
Let's just follow the steps:
- download latest [release version](https://github.com/keshon/kitsu-to-discord-task-notification/releases/tag/2024-01-21)
- unzip, go into the app folder 
- update conf.toml but only these fields (the rest keep by default):
```
[kitsu]
    hostname = "https://example.com/"
    email = "manager@example.com"
    password = "123"
    requestInterval = 1

[discord]
    webhookURL = "https://discord.com/api/webhooks/123/123456789"
```
- save it and run `app.exe`

**Comment by keshon** [comment]
The `requestInterval` set to 1 - it means the bot will check kitsu for new updates each minute (so the message in discord will appear after one minute since the event actually happened in Kitsu - it's a known limitation). 

Again: it's better to find out how to use build-in Discord integration feature in Kitsu

**Comment by Guscal** [comment]
well i found out my firewall was messing with the connection to your bot, we are goin to use it in the meantime, until we manage to make the official bot work

**Comment by Guscal** [comment]
Thank you soooo much

**Comment by Guscal** [comment]
> The `requestInterval` set to 1 - it means the bot will check kitsu for new updates each minute (so the message in discord will appear after one minute since the event actually happened in Kitsu - it's a known limitation).
> 
> Again: it's better to find out how to use build-in Discord integration feature in Kitsu

well im investigating if i have to code the actual bot because the documentation dosent mention any of that, it looks pretty straight foward so i dont know what im doing wrong if its that easy but, again thanks for the help  with your bot

**Comment by keshon** [comment]
https://kitsu.cg-wire.com/discord/
Just in case - this is the offical doc for discord integration.

If you still stuck - hop in to my Discord server (https://discord.gg/NVtdTka8ZT) - might help you out
